_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
                - 62
            "4": 3.12.3
            "5": 0.19.7
            "8":
                - 5
                - 9
            "12": 0.19.7
            "13": linux-x86_64
annotation_file:
    value: /home/dapgrad/tenzinl2/lumina/luminaData/processed_enron_paths_filtered.csv
batch_size:
    value: 1
epochs:
    value: 50
learning_rate:
    value: 0.001
mixed_precision:
    value: true
model_type:
    value: TableSense
num_gpus:
    value: 3
num_workers:
    value: 8
optimizer:
    value: Adam
